---
- name: linux os hardening
  hosts: all
  gather_facts: false
  roles:
    - os_hardening
  tags: hardening

- name: linux os tuning
  hosts: all
  gather_facts: false
  roles:
    - tuning
  tags: tuning

- name: linux os hardening
  hosts: all 
  gather_facts: false
  roles:
    - ssh_hardening
  tags: ssh

- name: Docker Installation
  hosts: all 
  gather_facts: false
  roles:
    - docker
  tags: install-docker

#- name: Docker Configuration
#  hosts: all 
#  gather_facts: false
#  roles:
#    - docker
#  tags: install-docker