---
- name: OS Harden And Service Install Playbook
  hosts: all
  become: true
  gather_facts: true
  tags: hardening
  roles:
    - hardening

- name: Install Docker
  hosts: all
  become: true
  gather_facts: true
  tags: docker
  roles:
    - docker
