all:

    vars:
        ansible_user: root

    children:
        web-servers:
            hosts:
                dp-nexus:
                    ansible_host: dp-nexus
                    ansible_port: 2285