all:
    children:
        web-servers:
            hosts:
                hetzner:
                    ansible_host: 159.69.179.148
                    ansible_user: root
                    ansible_port: 22

                sharif:
                    ansible_host: ip
                    ansible_user: root
                    ansible_port: 22