all:
    children:
        web-servers:
            hosts:
                sharif:
                    ansible_host: host-ip
                    ansible_user: user
                    ansible_port: port
                
                hetzner:
                    ansible_host: host-ip
                    ansible_user: user
                    ansible_port: port