all:

    vars:
        ansible_user: root

    children:
        web-servers:
            hosts:
                dp-0:
                    ansible_host: 213.233.177.29
                    ansible_port: 2220

                dp-1:
                    ansible_host: 213.233.177.229
                    ansible_port: 2221

                dp-2:
                    ansible_host: 213.233.177.229
                    ansible_port: 2222

                dp-nexus:
                    ansible_host: 213.233.177.229
                    ansible_port: 2285