all:
    children:
        web-servers:
            hosts:
                sharif:
                    ansible_host: 213.233.177.229
                    ansible_user: mhykari
                    ansible_port: 2285
                
                hetzner:
                    ansible_host: 159.69.179.148
                    ansible_user: root
                    ansible_port: 2285
