---

- name: Install Network Utility Packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes
  loop:
    - net-tools
    - nmap
    - dnsutils
    - resolvconf
    - tcpdump
    - mtr
    - ethtool
    - traceroute
    - scapy
  notify: apt update