all:
  children:
    repo-servers:
      hosts:
        dpa-0:
          ansible_host: dpa-0
          ansible_port: 22

        dpa-1:
          ansible_host: dpa-1
          ansible_port:
        dpa-2:
          ansible_host: dpa-2
          ansible_port: 22