---
- name: Download Trivy .deb package
  ansible.builtin.get_url:
    url: https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
    dest: /tmp/trivy_0.18.3_Linux-64bit.deb

- name: Install Trivy .deb package
  ansible.builtin.apt:
    deb: /tmp/trivy_0.18.3_Linux-64bit.deb
    state: present
  become: yes

- name: Clean up Trivy .deb package
  ansible.builtin.file:
    path: /tmp/trivy_0.18.3_Linux-64bit.deb
    state: absent

- name: Create Trivy result directory
  file:
    path: "{{ trivy_result_directory }}"
    state: directory
  become: true

- name: Ensure Trivy directory exists
  become: yes
  file:
    path: "{{ trivy_result_directory }}"
    state: directory

- name: Create daily cron job for Trivy
  ansible.builtin.cron:
    name: "Run Trivy daily"
    minute: "0"
    hour: "0"
    job: "/usr/local/bin/trivy filesystem --output /opt/services/trivy-result/trivy_$(date +\\%Y-\\%m-\\%d).log --exit-code 1 /"
    state: present
    mode: 0755
  notify: RestartCron
  tags: 
    - trivy