---
- name: Ensure directory trivy exists
  file:
    path: "{{ TRIVY_RESULT_DIRECTORY }}"
    state: directory
  register: dir_creation_result
  ignore_errors: true

- name: Notify handler if directory was created
  meta: flush_handlers
  when: dir_creation_result.changed

#- name: Trivy Installation
#  import_tasks: trivy_installation.yml

- name: Get Trivy version
  command: trivy --version
  register: trivy_version_output

- debug:
    msg: "Trivy version is {{ trivy_version_output.stdout }}"

- name: Copy trivy_scan.sh script to the destination server
  ansible.builtin.template:
    src: trivy_scan.sh.j2
    dest: "{{ TRIVY_RESULT_DIRECTORY }}/trivy_scan.sh"
    mode: "0755"  # Ensure the script is executable

- name: Add Trivy scan command to crontab
  cron:
    name: "Run Trivy scan"
    minute: 0
    hour: 0
    job: "{{ TRIVY_RESULT_DIRECTORY }}/trivy_scan.sh"
    state: present
  notify: RestartCron