---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Download Trivy .deb package
  ansible.builtin.get_url:
    url: https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
    dest: /tmp/trivy_0.18.3_Linux-64bit.deb

- name: Install Trivy .deb package
  ansible.builtin.apt:
    deb: /tmp/trivy_0.18.3_Linux-64bit.deb
    state: present
  become: yes

- name: Clean up Trivy .deb package
  ansible.builtin.file:
    path: /tmp/trivy_0.18.3_Linux-64bit.deb
    state: absent


- name: Create Trivy result directory
  file:
    path: "{{ trivy_result_directory }}"
    state: directory
  become: true

- name: Ensure Trivy directory exists
  become: yes
  file:
    path: "{{ trivy_result_directory }}"
    state: directory

- name: Create Trivy cronjob
  become: yes
  cron:
    name: Run Trivy scan
    minute: 0
    hour: 0
    job: /opt/services/trivy_scan.sh
    mode: 0755
    state: present
  notify: RestartCron
  tags: 
    - trivy