---
- name: remove /tmp from fstab
  become: true
  mount:
    path: /tmp
    state: absent
  tags:
    - fstab

- name: remove floppy from fstab
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: "^(.*)floppy(.*)$"
  tags:
    - fstab
