---
- name: Ensure NTP package is installed
  package:
    name: ntp
    state: present

- name: Copy NTP configuration file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - Restart ntp
