- name: Create ssh config directory
  file:
    path: etc/ssh
    state: directory

- name: Create a ssh config file
  file:
    path: etc/ssh/sshd_config
    state: touch
    mode: 0644

- name: Add hardened SSH config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Reload SSH
