---
- name: Install Trivy
  apt:
    name: trivy
    state: present
  become: true

- name: Create Trivy result directory
  file:
    path: "{{ trivy_result_directory }}"
    state: directory
  become: true

- name: Ensure Trivy directory exists
  become: yes
  file:
    path: "{{ trivy_result_directory }}"
    state: directory

- name: Create Trivy cronjob
  become: yes
  cron:
    name: Run Trivy scan
    minute: 0
    hour: 0
    job: /opt/services/trivy_scan.sh
    mode: 0755
    state: present
  notify: RestartCron
  tags: 
    - trivy