---
galaxy_info:
  author: Sebastian Gumprich
  description: This Ansible role provides numerous security-related ssh configurations, providing all-round base protection.
  company: Hardening Framework Team
  license: Apache License 2.0
  min_ansible_version: 2.9.10
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - system
    - security
    - hardening
dependencies: []
