---
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: ensure docker-compose-plugin is at the latest version
  apt:
    name: docker-compose-plugin
    state: latest
    update_cache: yes
  tags: inatall_compose