---
- name: Install the package for strong password checking
  ansible.builtin.apt:
    name: libpam-passwdqc
    state: present
    update_cache: true
  when:
    - os_auth_pam_passwdqc_enable

- name: Configure passwdqc
  ansible.builtin.template:
    src: usr/share/pam-configs/pam_passwdqc.j2
    dest: "{{ passwdqc_path }}"
    mode: "0644"
    owner: root
    group: root
  when:
    - os_auth_pam_passwdqc_enable

- name: Update pam on Debian systems
  ansible.builtin.command: pam-auth-update --package
  environment:
    DEBIAN_FRONTEND: noninteractive
  changed_when: false

- name: Remove passwdqc
  ansible.builtin.apt:
    name: libpam-passwdqc
    state: absent
  when:
    - not os_auth_pam_passwdqc_enable
