all:
  vars:
    ansible_user: root
  children:
    dp:
      hosts:
        dp-tools:
          ansible_host: dp-tools
          ansible_port: 2285

        dp-monlog:
          ansible_host: dp-monlog
          ansible_port: 2221

        dp-2:
          ansible_host: dp-2
          ansible_port: 2222

        me:
          ansible_host: 127.0.0.1
          ansible_port: 22