all:
  vars:
 
    ansible_user: root
  children:
    dp:
      hosts:
        dp-tools:
          ansible_host: do-tools
          ansible_port: 2285

        dp-monlog:
          ansible_host: do-monlgo
          ansible_port: 2221